* Five Skills Entrepreneurs Need

/Source/: [[http://www.readwriteweb.com/start/2011/09/five-types-of-skills-you-need-entrepreneurs.php][Five types of skills entrepreneurs need]]

1. *Be healthy*. Are startups all about pulling all nighters and eating
   ramen noodles? Steve Jobs wasn't like that in his early days,
   Metcalfe argues. You need to be healthy. "Don't buy into this
   bullshit that you need to drive yourself into the ground," he
   said. "You should sleep eight hours a day. The trick is to figure
   out when you need to get up and then go to sleep eight hours before
   that."

2. *Writing*. Lots of people have great stories that get left in the
   bar, Jack London once said. Metcalfe says entrepreneurs should
   develop writing skills by writing about what they are doing all the
   time - it's an important part of thinking, communicating and
   selling.

3. *Speaking*. "I have given more speeches...than you have," Metcalfe
   joked. You have to be a good speaker, he says. Speak every chance
   you can and get better at it. Metcalfe is very good at it.

4. *Selling*. Startups don't value sales people and skills highly
   enough, Metcalfe argues. Even engineers need to be able to sell
   their ideas internally and they need to be able to gather resources
   from inside and outside their companies.

5. *Planning*. "You can't change your plan if you don't have one,"
   Metcalfe says. You need a process for regularly reviewing your
   plans.
